language: python
python:
    - "2.7"
    - "3.5"
sudo: required
services:
    - docker
env:
    - OC_VERSION=8.1
    - OC_VERSION=8.2
    - OC_VERSION=9.0
    - OC_VERSION=9.1

before_install:
    - travis-build/setup_oc_docker.sh $OC_VERSION

install:
    - pip install requests unittest-data-provider six

script:
    - cp owncloud/test/config.py.sample owncloud/test/config.py
    # execute unit tests
    - ./runtests.sh

